Repository BanklessDAO/DEGEN, pull requests merged in 2021-10, with the labels that each got.

#164 Use builder pattern in unit tests
  package.json
  src/test/service/poap/StartPOAP.test.ts
  src/test/utils/ServiceUtils.test.ts
  yarn.lock
Labels: enhancement

#165 Release/1.6.0
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-qa.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  docs/BOT_PERMISSIONS.md
  jest-mongodb-config.js
  jest.config.js
  package.json
  pm2.config.js
  src/app/app.ts
  src/app/commands/help/Help.ts
  src/app/commands/poap/POAP.ts
  src/app/events/GuildBanRemove.ts
  src/app/events/GuildMemberAdd.ts
  src/app/events/GuildMemberUpdate.ts
  src/app/events/Ready.ts
  src/app/events/UserUpdate.ts
  src/app/events/poap/AddUserForEvent.ts
  src/app/service/bounty/DeleteBounty.ts
  src/app/service/bounty/create/CreateNewBounty.ts
  src/app/service/bounty/create/PublishBounty.ts
  src/app/service/constants/constants.ts
  src/app/service/help/HowToBounty.ts
  src/app/service/help/HowToPOAP.ts
  src/app/service/notion/__mocks__/RetrieveFAQs.ts
  src/app/service/poap/EndPOAP.ts
  src/app/types/discord/Allowlist.ts
  src/app/utils/BountyUtils.ts
  src/app/utils/Confusables.ts
  src/app/utils/POAPUtils.ts
  src/app/utils/ServiceUtils.ts
  src/test/commands/admin/GuestPass.test.ts
  src/test/commands/notion/NotionFAQs.test.ts
  src/test/commands/notion/RetrieveFAQs.test.ts
  src/test/service/bounty/claim.test.ts
  src/test/service/bounty/list.test.ts
  src/test/service/poap/StartPOAP.test.ts
  src/test/utils/BountyUtils.test.ts
  src/test/utils/ServiceUtils.test.ts
  yarn.lock
Labels: bug, documentation, enhancement, Administration

#167 Hotfix/1.6.2
  CHANGELOG.md
  package.json
  src/app/events/GuildBanRemove.ts
  src/app/events/GuildMemberAdd.ts
  src/app/events/GuildMemberUpdate.ts
  src/app/events/MessageCreate.ts
  src/app/events/MessageReactionAdd.ts
  src/app/events/Ready.ts
  src/app/events/UserUpdate.ts
  src/app/events/VoiceStateUpdate.ts
  src/app/events/chat/MessageCreateOnDEGEN.ts
Labels: bug

#187 Hotfix/1.7.2
  .github/workflows/deploy-prod.yml
  .github/workflows/do-deployment.bak
  CHANGELOG.md
  Procfile
  package.json
  yarn.lock
Labels: bug

#196 Feature/auto end poap event
  .env.prod
  .env.qa
  .env.template
  CHANGELOG.md
  README.md
  package.json
  src/app/commands/poap/POAP.ts
  src/app/events/Ready.ts
  src/app/events/poap/AddUserForEvent.ts
  src/app/schema/poap/poapSettings.json
  src/app/service/constants/constants.ts
  src/app/service/guest-pass/GuestPassService.ts
  src/app/service/poap/EndPOAP.ts
  src/app/service/poap/POAPService.ts
  src/app/service/poap/StartPOAP.ts
  src/app/utils/Log.ts
  src/app/utils/POAPUtils.ts
Labels: enhancement, POAP
