Repository BanklessDAO/DEGEN, pull requests merged in 2021-11, with the labels that each got.

#225 Hot fix/coordinape form request
  CHANGELOG.md
  src/app/service/coordinape/CoordinapeSendForm.ts
Labels: Administration

#227 Feature/twitter spaces integration
  .env.prod
  .env.qa
  .env.template
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-qa.yml
  .github/workflows/deploy-uat.yml
  CHANGELOG.md
  assets/profile.jpg
  package.json
  src/app/api/EventsAPI.ts
  src/app/commands/admin/Account.ts
  src/app/commands/poap/POAP.ts
  src/app/events/GuildBanRemove.ts
  src/app/events/Ready.ts
  src/app/events/bounty/MessageCreateOnBountyBoard.ts
  src/app/events/poap/AddUserForEvent.ts
  src/app/schema/poap/discordServers.json
  src/app/schema/poap/discordUsers.json
  src/app/schema/poap/poapAttendeesTwitterSpaces.json
  src/app/schema/poap/poapSettingsTwitterSpaces.json
  src/app/service/account/VerifyTwitter.ts
  src/app/service/bounty/ClaimBounty.ts
  src/app/service/bounty/CompleteBounty.ts
  src/app/service/bounty/DeleteBounty.ts
  src/app/service/bounty/ListBounty.ts
  src/app/service/bounty/ReCreateBounty.ts
  src/app/service/bounty/RefreshBounty.ts
  src/app/service/bounty/SeekHelpBounty.ts
  src/app/service/bounty/SubmitBounty.ts
  src/app/service/bounty/UpdateEditKeyBounty.ts
  src/app/service/bounty/create/CreateNewBounty.ts
  src/app/service/bounty/create/PublishBounty.ts
  src/app/service/constants/apiKeys.ts
  src/app/service/constants/constants.ts
  src/app/service/guest-pass/AddGuestPass.ts
  src/app/service/guest-pass/GuestPassService.ts
  src/app/service/guest-pass/RemoveGuestPass.ts
  src/app/service/poap/ClaimPOAP.ts
  src/app/service/poap/ConfigPOAP.ts
  src/app/service/poap/DistributePOAP.ts
  src/app/service/poap/EndPOAP.ts
  src/app/service/poap/POAPService.ts
  src/app/service/poap/SchedulePOAP.ts
  src/app/service/poap/StartPOAP.ts
  src/app/service/scoap-squad/ScoapDatabase.ts
  src/app/service/timecard/Checkin.ts
  src/app/service/timecard/Checkout.ts
  src/app/service/timecard/Hours.ts
  src/app/types/nextauth/NextAuthAccountCollection.ts
  src/app/types/poap/POAPTwitterParticipants.ts
  src/app/types/poap/POAPTwitterSettings.ts
  src/app/types/poap/POAPUnclaimedParticipants.ts
  src/app/utils/MongoDbUtils.ts
  src/app/utils/POAPUtils.ts
  src/app/utils/ServiceUtils.ts
  src/app/utils/dbUtils.ts
  yarn.lock
Labels: bug, enhancement, POAP

#163 I update CONTRIBUTING docs.
  docs/CONTRIBUTING.md
Labels: documentation

#236 Hotfix/1.9.2
  CHANGELOG.md
  package.json
  src/app/commands/help/Help.ts
  src/app/commands/poap/POAP.ts
  src/app/service/help/HowToPOAP.ts
  src/app/service/poap/DistributePOAP.ts
  src/app/service/poap/EndPOAP.ts
Labels: bug, enhancement

#239 fix parsing error and logdna token
  CHANGELOG.md
  package.json
  src/app/events/poap/AddUserForEvent.ts
  src/app/service/poap/EndPOAP.ts
  src/app/utils/Log.ts
Labels: bug

#207 Feature/first quest
  .env.prod
  .env.qa
  CHANGELOG.md
  package.json
  src/app/commands/first-quest/FirstQuest.ts
  src/app/events/GuildMemberAdd.ts
  src/app/events/GuildMemberRemove.ts
  src/app/events/MessageCreate.ts
  src/app/events/Ready.ts
  src/app/events/first-quest/messageLaunchFirstQuest.ts
  src/app/schema/first-quest/firstQuestContent.json
  src/app/schema/first-quest/firstQuestPOAPs.json
  src/app/schema/first-quest/firstQuestTracker.json
  src/app/service/constants/channelIds.ts
  src/app/service/constants/constants.ts
  src/app/service/constants/firstQuest.ts
  src/app/service/constants/roleIds.ts
  src/app/service/first-quest/ConfigureFirstQuest.ts
  src/app/service/first-quest/FirstQuestPOAP.ts
  src/app/service/first-quest/FirstQuestRescueService.ts
  src/app/service/first-quest/LaunchFirstQuest.ts
  src/app/utils/FirstQuestUtils.ts
  yarn.lock
Labels: enhancement

#240 Temp/sync branches
  CHANGELOG.md
  package.json
  src/app/commands/help/Help.ts
  src/app/commands/poap/POAP.ts
  src/app/events/poap/AddUserForEvent.ts
  src/app/service/help/HowToPOAP.ts
  src/app/service/poap/ClaimPOAP.ts
  src/app/service/poap/ConfigPOAP.ts
  src/app/service/poap/DistributePOAP.ts
  src/app/service/poap/EndPOAP.ts
  src/app/service/poap/SchedulePOAP.ts
  src/app/service/poap/StartPOAP.ts
  src/app/utils/Log.ts
  src/app/utils/POAPUtils.ts
Labels: enhancement

#247 Feature/end twitter space
  CHANGELOG.md
  src/app/commands/poap/POAP.ts
  src/app/service/account/VerifyTwitter.ts
  src/app/service/poap/ClaimPOAP.ts
  src/app/service/poap/DistributePOAP.ts
  src/app/service/poap/EndPOAP.ts
  src/app/service/poap/StartPOAP.ts
  src/app/utils/POAPUtils.ts
Labels: enhancement, POAP

#260 Feature/twitter space cleanup
  .env.prod
  .env.qa
  CHANGELOG.md
  assets/drafts/IMG_1152.jfif
  assets/drafts/Mockup_1.jpg
  assets/drafts/Mockup_2.jpg
  docs/BOT_PERMISSIONS.md
  src/app/commands/poap/POAP.ts
  src/app/events/Ready.ts
  src/app/events/poap/AddUserForEvent.ts
  src/app/service/account/VerifyTwitter.ts
  src/app/service/poap/ClaimPOAP.ts
  src/app/service/poap/DistributePOAP.ts
  src/app/service/poap/EndPOAP.ts
  src/app/service/poap/POAPService.ts
  src/app/service/poap/StartPOAP.ts
  src/app/utils/POAPUtils.ts
Labels: POAP

#265 Feature/channel only flow
  CHANGELOG.md
  src/app/commands/admin/Account.ts
  src/app/commands/poap/POAP.ts
  src/app/events/poap/AddUserForEvent.ts
  src/app/service/account/VerifyTwitter.ts
  src/app/service/poap/ClaimPOAP.ts
  src/app/service/poap/ConfigPOAP.ts
  src/app/service/poap/DistributePOAP.ts
  src/app/service/poap/EndPOAP.ts
  src/app/service/poap/POAPService.ts
  src/app/service/poap/SchedulePOAP.ts
  src/app/service/poap/StartPOAP.ts
  src/app/service/poap/start/StartChannelFlow.ts
  src/app/service/poap/start/StartPOAP.ts
  src/app/service/poap/start/StartTwitterFlow.ts
  src/app/utils/POAPUtils.ts
  src/app/utils/ServiceUtils.ts
Labels: enhancement, POAP
